project "CodeGenerator"
    kind"ConsoleApp"
    language"C++"
    cppdialect"C++17"
    staticruntime"off"
    toolset"clang"
    targetdir("../bin/"..outputdir.."/%{prj.name}")
    objdir("../bin-int/"..outputdir.."/%{prj.name}")
    files{
        "Src/**.h",
        "Src/**.cpp",
        "LLVM/include/clang-c/index.h",
    }
    includedirs{
        "LLVM/include",
        "Src",
    }
    links{
        "libclang.lib"
    }
    libdirs{
        "LLVM/lib",
    }
    filter"configurations:Debug"
		runtime"Debug"
		symbols"on"
	filter"configurations:Release"
		runtime"Release"
		optimize"on"