project "Reflect"
    kind"SharedLib"
    language"C++"
    cppdialect"C++17"
    staticruntime"off"
    targetdir("../bin/"..outputdir.."/%{prj.name}")
    objdir("../bin-int/"..outputdir.."/%{prj.name}")
    files{
        "Src/**.h",
        "Src/**.cpp",
        "GeneratedCode/**.h",
        "GeneratedCode/**.cpp",
    }
    includedirs{
        "GeneratedCode",
        "Src",
        "../%{prj.name}"
    }
    libdirs{
        "LLVM/lib",
    }
    filter"configurations:Debug"
		runtime"Debug"
		symbols"on"
	filter"configurations:Release"
		runtime"Release"
		optimize"on"